const playersData = [
    // ARQUEROS
    { id: 1, name: 'EMILIANO MARTÍNEZ', position: 'Arquero', category: 'arquero' },
    { id: 2, name: 'GERÓNIMO RULLI', position: 'Arquero', category: 'arquero' },
    { id: 3, name: 'JUAN MUSSO', position: 'Arquero', category: 'arquero' },
    { id: 4, name: 'WALTER BENÍTEZ', position: 'Arquero', category: 'arquero' },
    { id: 5, name: 'FACUNDO CAMBESES', position: 'Arquero', category: 'arquero' },
    { id: 6, name: 'SANTIAGO BELTRAN', position: 'Arquero', category: 'arquero' },

    // DEFENSORES
    { id: 7, name: 'AGUSTÍN GIAY', position: 'Lateral derecho', category: 'defensor' },
    { id: 8, name: 'GONZALO MONTIEL', position: 'Lateral derecho', category: 'defensor' },
    { id: 9, name: 'NAHUEL MOLINA', position: 'Lateral derecho', category: 'defensor' },
    { id: 10, name: 'NICOLÁS CAPALDO', position: 'Lateral derecho', category: 'defensor' },
    { id: 11, name: 'KEVIN MAC ALLISTER', position: 'Lateral derecho', category: 'defensor' },
    { id: 12, name: 'LUCAS MARTINEZ QUARTA', position: 'Defensor central', category: 'defensor' },
    { id: 13, name: 'MARCOS SENESI', position: 'Defensor central', category: 'defensor' },
    { id: 14, name: 'LISANDRO MARTÍNEZ', position: 'Defensor central', category: 'defensor' },
    { id: 15, name: 'NICOLÁS OTAMENDI', position: 'Defensor central', category: 'defensor' },
    { id: 16, name: 'GERMÁN PEZZELLA', position: 'Defensor central', category: 'defensor' },
    { id: 17, name: 'LEONARDO BALERDI', position: 'Defensor central', category: 'defensor' },
    { id: 18, name: 'CRISTIAN ROMERO', position: 'Defensor central', category: 'defensor' },
    { id: 19, name: 'LAUTARO DI LOLLO', position: 'Defensor central', category: 'defensor' },
    { id: 20, name: 'ZAID ROMERO', position: 'Defensor central', category: 'defensor' },
    { id: 21, name: 'FACUNDO MEDINA', position: 'Defensor central', category: 'defensor' },
    { id: 22, name: 'MARCOS ACUÑA', position: 'Lateral izquierdo', category: 'defensor' },
    { id: 23, name: 'NICOLÁS TAGLIAFICO', position: 'Lateral izquierdo', category: 'defensor' },
    { id: 24, name: 'GABRIEL ROJAS', position: 'Lateral izquierdo', category: 'defensor' },

    // MEDIOCAMPISTAS
    { id: 25, name: 'MÁXIMO PERRONE', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 26, name: 'LEANDRO PAREDES', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 27, name: 'GUIDO RODRÍGUEZ', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 28, name: 'ANÍBAL MORENO', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 29, name: 'MILTON DELGADO', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 30, name: 'ALAN VARELA', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 31, name: 'EZEQUIEL FERNÁNDEZ', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 32, name: 'RODRIGO DE PAUL', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 33, name: 'EXEQUIEL PALACIOS', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 34, name: 'ENZO FERNÁNDEZ', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 35, name: 'ALEXIS MAC ALLISTER', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 36, name: 'GIOVANI LO CELSO', position: 'Mediocampista ofensivo', category: 'mediocampista' },
    { id: 37, name: 'NICOLÁS DOMÍNGUEZ', position: 'Mediocampista central', category: 'mediocampista' },
    { id: 38, name: 'EMILIANO BUENDIA', position: 'Mediocampista ofensivo', category: 'mediocampista' },
    { id: 39, name: 'VALENTÍN BARCO', position: 'Lateral / Medio', category: 'mediocampista' },

    // DELANTEROS
    { id: 40, name: 'NICOLÁS PAZ', position: 'Delantero / Mediapunta', category: 'delantero' },
    { id: 41, name: 'FRANCO MASTANTUONO', position: 'Delantero / Mediapunta', category: 'delantero' },
    { id: 42, name: 'THIAGO ALMADA', position: 'Delantero / Mediapunta', category: 'delantero' },
    { id: 43, name: 'LIONEL MESSI', position: 'Extremo derecho', category: 'delantero' },
    { id: 44, name: 'TOMÁS ARANDA', position: 'Extremo', category: 'delantero' },
    { id: 45, name: 'NICOLÁS GONZÁLEZ', position: 'Extremo derecho', category: 'delantero' },
    { id: 46, name: 'ALEJANDRO GARNACHO', position: 'Extremo izquierdo', category: 'delantero' },
    { id: 47, name: 'GIULIANO SIMEONE', position: 'Extremo derecho', category: 'delantero' },
    { id: 48, name: 'MATÍAS SOULÉ', position: 'Extremo derecho', category: 'delantero' },
    { id: 49, name: 'CLAUDIO ECHEVERRI', position: 'Mediapunta', category: 'delantero' },
    { id: 50, name: 'GIANLUCA PRESTIANNI', position: 'Extremo', category: 'delantero' },
    { id: 51, name: 'SANTIAGO CASTRO', position: 'Delantero centro', category: 'delantero' },
    { id: 52, name: 'LAUTARO MARTÍNEZ', position: 'Delantero centro', category: 'delantero' },
    { id: 53, name: 'JOSÉ MANUEL LÓPEZ', position: 'Extremo izquierdo', category: 'delantero' },
    { id: 54, name: 'JULIÁN ÁLVAREZ', position: 'Delantero centro', category: 'delantero' },
    { id: 55, name: 'MATEO PELLEGRINO', position: 'Delantero centro', category: 'delantero' }
];
